[package]
name = "solve_game"
edition = "2024.beta" # edition = "legacy" to use legacy (pre-2024) Move

[dependencies.game]
local = "../game"

[addresses]
solve_game = "0x0"
sui = "0x2"
game = "0x2e5ba180f53d8aa73de26e03435abe6ac8f182a383ce8a99f4aaca8a76fc7979"