[package]
name = "week2"
edition = "2024.beta"
published-at = "0x0d026a32bba57cfeeac87571bdd1913f0ace336eb40744ac7e9150a59ef87911"

[dependencies]
Sui = { git = "https://gitee.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }

[addresses]
week2 = "0x0d026a32bba57cfeeac87571bdd1913f0ace336eb40744ac7e9150a59ef87911"
sui = "0x2"